# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cce9f78c4cbd55b485272a33fad8160eeb8f19ad5285d0a696011265dce102a907ae879991615abc07ed519a6428af8cb4ce259cecdcf2a16669a71a53f20927

test:
  secret_key_base: d9293346c9660bb747c397f549abc6f89f5ccd5749ed5addae616567e4cf9c8958c954103e7cac8d4a2f4df2c533c69dc3ab737554881c9f3ecf7d694d325302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
